#! /bin/bash

find . -name "*.pyc" -delete
echo "Generating docs"
PYTHONPATH=./phi pdoc --html-dir=docs --html phi --only-pypath --overwrite
echo "Making README.md"
python scripts/create_readme.py
echo "Finished"